#!/usr/bin/env ruby
ENV['RACK_ENV'] ||= ARGV[0] || "development"

ARGV.clear # Don't pass args to irb

require 'rubygems'
require 'pancake'

Pancake.root = Pancake.get_root(__FILE__, "..")

# Load the <%= stack_class.camel_case %> stack
require File.join(Pancake.root, "..", "<%= stack_class %>")
Pancake::Console.new(<%= stack_class.camel_case %>)


